version: '3'

services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
    command: npm run dev

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data

volumes:
  node_modules:
  redis_data: