version: '3'

services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    command: npm run dev

volumes:
  node_modules: