version: '3'

services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  app:
    image: pharanyuchangsan/gitlabdeploynoti:prod
    volumes:
      - node_modules:/src/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

volumes:
  node_modules: